# Generated by Django 6.0.8 on 2026-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_post_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
    ]
